### ISSUE TITLE
Migrate from Restify to Restler

### ISSUE THREAD

**Issue by Echo3ToEcho7** [dynamicdan/sn-filesync#22]
In order to remove the need for a compiler, I have started a [fork](https://github.com/Echo3ToEcho7/filesync/tree/restler) that uses restler instead of restify.

Thoughts?

**Comment by dynamicdan** [comment]
What compiler is actually needed? NPM still does all the installing?

**Comment by Echo3ToEcho7** [comment]
Restify uses dtrace-provider which is a native module and needs a C++ compiler installed. NPM will still install it, but will fail doing the install if there is no C++ compiler (like gcc or llvm) installed. I always have Xcode installed on my Mac so it isn't an issue for me, but not all of the SNow developers that I work with have a compiler on their computer.

**Comment by dynamicdan** [comment]
experimental branch now contains your fork. Initial testing seems fine. 1 part needs re-testing for dodgy https/SSL setups. I will test this branch a bit more before merging it in to master.
Thanks for the awesome upgrade!
