### ISSUE TITLE
Record with multiple scripts/css/xml does not download with search/download

### ISSUE THREAD

**Issue by TheSpeedReeder** [dynamicdan/sn-filesync#25]
I have a custom record that has 3 scripts.  I can setup the config file to handle each and they work separately however when using --search and --download, they are not all created.   Only one will be created.

Touching the appropriate files that were not created will cause the sync to happen correctly, there is just no way for the --search --download to do it for the user.

**Comment by ReedOwens** [comment]
I have this fixed and will send the proposed changes
