### ISSUE TITLE
Mention contributors because THEY are AWESOME

### ISSUE THREAD

**Issue by dynamicdan** [dynamicdan/sn-filesync#28]
Update Read me with new section!
Update package.json ?

@ReedOwens
@Echo3ToEcho7 
@dwightgunning 
@karimhernandez 
@stegel

**Comment by ReedOwens** [comment]
Dan,

Can we chat via email or a chat?  My email is Reed.Owens@UXstorm.com.  Would like to discuss some changes I would like to do to this project or create a new one if it's too different.  I would like to get your thoughts.

BTW: Thanks for the mention and thanks for putting me on the contributors  I plan on more than bug fixes..
