### ISSUE TITLE
Files sync but can't push.

### ISSUE THREAD

**Issue by designedbydave** [dynamicdan/sn-filesync#40]
Trying to sync my demo instance and it pulls all the records but I'm unable to sync my changes back to the server.

It says it's watching for changes.
```
16:46:41 - info: *********** Watching for changes ***********
16:46:41 - info: Created folders required for syncing records
```

Not sure if I setup my configuration wrong. 

Any thoughts? 

Edit: I am using the 'Geneva' release of ServiceNow. 

Edit #2: Finally got it working, I had to delete my original config file. However, I get a
```
12:59:05 - warn: No map
```

Not sure what this means? my folder structure is there.

**Comment by dynamicdan** [comment]
Hi,

I think you have a problem with your config file. You need to do some basic troubleshooting. 

Try a --search on the command line. This should confirm your connection is correct. 

There is also a --test option to test the code base. It adds a comment to the JSUtil script include (harmless). 

Make sure your watcher is watching the correct folder. Shouldn't be an issue if files are being saved where you expect them to be. 

Note that the "map" refers to the folder config that identifies which table relates to which folder. There is a default config for this that can be overridden. Everything is documented in the readme. 

Good luck! Add your findings/solution here and I can add this as a troubleshooting entry.

**Comment by dynamicdan** [comment]
I found out what "no map" is. It's when a file exists but the config doesn't have any folder mapping for it. I've added some more debug/warn messages to help others understand this issue better next time.

In short, you may be missing a table mapping entry in your config file.

**Comment by designedbydave** [comment]
@dynamicdan thanks! If I encounter anything I'll let you know.
