### ISSUE TITLE
Meaning of records_per_search

### ISSUE THREAD

**Issue by chovanecm** [dynamicdan/sn-filesync#48]
Hi,
I'd like to ask why one would want to limit the number of records in a search? (the `records_per_search` option)
If the reason is performance, ServiceNow supports pagination (you can download e.g. 100 rows and then continue with next 100 rows; the server sends the URL for the next page in response headers).

Or is there any other reason?

Thanks

**Comment by dynamicdan** [comment]
Good question.
Mainly performance/paranoia reasons. For testing, the value is set to 1. This option/parameter has multiple use cases I believe. IIRC, one can search via sys_id that should only return 1 result. In other cases, some queries with a sort order of date DESC would desire the first/newest record to match on.
